version: 2

defaults:
  docker:
    - image: circleci/node:10

jobs:
    build:
        steps:
        - checkout
        - run:
              name: install
              command: npm install
        - run:
              name: build
              command: npm run build
        - run:
              name: docs
              command: npm run docs
        - run:
              name: test
              command: npm test
    publish:
        steps:
        - run:
              name: update npm version
              command: npm version $CIRCLE_TAG
        - run:
              name: authenticate with npm
              command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        - run:
              name: publish package
              command: npm publish
workflows:
    version: 2
    build-publish:
        jobs:
          - build:
              filters:
                tags:
                  only: /^v.*/
                branches:
                  ignore: /.*/
          - publish:
              requires:
                - build

