version: 2

defaults:
  docker:
    - image: circleci/node:10

jobs:
    build:
        steps:
        - checkout
        - run:
              name: install
              command: npm install
        - run:
              name: build
              command: npm run build
        - run:
              name: docs
              command: npm run docs
        - run:
              name: test
              command: npm test
    major:
        steps:
        - run:
              name: update version
              command: npm major
    publish:
        - run:
              name: authenticate with npm
              command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/app/.npmrc
        - run:
              name: publish package
              command: npm publish
workflows:
    version: 2
    build-publish:
        jobs:
          - build
          - major:
              requires:
                - build
              filters:
                tags:
                  only: /^v.?/
          -minor:
              requires:
                - build
              filters:
                tags:
                  only: /^v.?/
          - publish:
              requires:
                - build
              filters:
                tags:
                  only: /^v.*/
                branches:
                  ignore: /.*/
